DELETE http://localhost:3001/api/blogs/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0IFVzZXIiLCJpZCI6MSwiaWF0IjoxNzMyNTc1ODIwLCJleHAiOjE3MzI1Nzk0MjB9.cH6SfNcQle3Z16VN6nEMHndk_gTuqjgp26oATQM3Cr0

###
PUT http://localhost:3001/api/blogs/1
content-type:application/json

{
  "likes": "a"
} 

###
POST http://localhost:3001/api/blogs
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0IFVzZXIiLCJpZCI6MSwiaWF0IjoxNzMyNjU2MjU4LCJleHAiOjE3MzI2NTk4NTh9.apUkHV825ILDiURj_k3vgdXBhqSpNtxeRDssTjZwR48

{
  "author":"Another Author",
  "title": "React",
  "url":"test.com",
  "likes": 5
}

###
POST http://localhost:3001/api/users
content-type:application/json

{
  "name": "User 2",
  "username": "testuser2@gmail.com",
  "password": "password"
}

###
DELETE http://localhost:3001/api/users/1

###
PUT http://localhost:3001/api/users/
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVwZGF0ZWR0ZXN0dXNlcm5hbWUiLCJuYW1lIjoiVGVzdCBVc2VyIiwiaWQiOjIsImlhdCI6MTczMjIzNDgzMSwiZXhwIjoxNzMyMjM4NDMxfQ.R0kC2B-i5ziyTNl-gb7Fb3qYgk8o9XJyISppKyeX9UU

{
  "username": "updatedtestusername"
} 

###
POST http://localhost:3001/api/login
content-type:application/json

{
  "username": "testuser@gmail.com",
  "password": "password"
}